// app/register/page.tsx
"use client";

import createUserDoc from "@/utils/db/account/createUserDoc";
import Notification from "@/components/general/notification";
import { useAuthContext } from "@/lib/context/authContext";
import googleSignIn from "@/utils/firebase/googleSignIn";
import emailSignIn from "@/utils/firebase/emailSignIn";
import Button from "@/components/general/button";
import Input from "@/components/general/input";
import { useRouter } from "next/navigation";
import { useState } from "react";

export default function Register() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [passwordConfirm, setPasswordConfirm] = useState("");

  const [notification, setNotification] = useState(false);
  const [notificationTitle, setNotificationTitle] = useState("");
  const [notificationType, setNotificationType] = useState<"success" | "error">(
    "success",
  );
  const [notificationMessage, setNotificationMessage] = useState("");

  const { user } = useAuthContext() as { user: any };
  const router = useRouter();

  const signUpWithGoogle = async () => {
    try {
      await googleSignIn();
      await createUserDoc(user);
      router.push("/account/diaries");
    } catch (err: any) {
      setNotification(true);
      setNotificationTitle("Error");
      setNotificationType("error");
      setNotificationMessage(err.message);
    }
  };

  const signUpWithEmail = async () => {
    if (email === "" || password === "" || passwordConfirm === "") {
      setNotification(true);
      setNotificationTitle("Error");
      setNotificationType("error");
      setNotificationMessage("Please fill in all fields");
      return;
    }

    const emailRegex = /\S+@\S+\.\S+/;
    if (!emailRegex.test(email)) {
      setNotification(true);
      setNotificationTitle("Error");
      setNotificationType("error");
      setNotificationMessage("Please enter a valid email");
      return;
    }

    if (password !== passwordConfirm) {
      setNotification(true);
      setNotificationTitle("Error");
      setNotificationType("error");
      setNotificationMessage("Passwords do not match");
      return;
    }

    const result = await emailSignIn(email, password);
    if (result[0] === "success") {
      await createUserDoc(result[1]);
      router.push("/account/diaries");
    } else {
      setNotification(true);
      setNotificationTitle("Error");
      setNotificationType("error");
      setNotificationMessage(result[1]);
    }
  };

  return (
    <>
      <h1 className="mb-5 text-center font-serif text-5xl text-primary">
        Create an Account
      </h1>
      <main className="flex flex-col gap-5">
        <Input
          value={email}
          placeholder="Email"
          type="email"
          vModel="email"
          updateValue={setEmail}
        />
        <Input
          value={password}
          placeholder="Password"
          type="password"
          vModel="password"
          updateValue={setPassword}
        />
        <Input
          value={passwordConfirm}
          placeholder="Confirm Password"
          type="password"
          vModel="password"
          updateValue={setPasswordConfirm}
        />
        <div className="flex justify-center gap-2 max-xs:flex-col">
          <Button title="Sign Up" onClick={signUpWithEmail} />
          <Button title="Sign Up With Google" onClick={signUpWithGoogle} />
        </div>
      </main>
      {notification ? (
        <Notification
          title={notificationTitle}
          type={notificationType}
          message={notificationMessage}
          timeout={5000}
          updateNotification={(value) => setNotification(value)}
        />
      ) : null}
    </>
  );
}

// src/views/Register.vue
<template>
  <h1 class="mb-5 text-center font-serif text-5xl text-primary">
    Create an Account
  </h1>
  <main class="flex flex-col gap-5">
    <input
      type="email"
      placeholder="Email"
      class="rounded-lg border-none bg-light-background placeholder:text-primary placeholder:opacity-40 focus:ring-primary"
      v-model="email"
    />
    <input
      type="password"
      placeholder="Password"
      class="rounded-lg border-none bg-light-background placeholder:text-primary placeholder:opacity-40 focus:ring-primary"
      v-model="password"
    />
    <input
      type="password"
      placeholder="Confirm Password"
      class="rounded-lg border-none bg-light-background placeholder:text-primary placeholder:opacity-40 focus:ring-primary"
      v-model="passwordConfirm"
    />
    <div class="flex justify-center gap-2">
      <button
        @click="signUpWithEmail"
        class="w-2/6 rounded-lg bg-black p-3 text-lg tracking-wide transition-all hover:text-primary active:tracking-widest max-sm:w-full"
      >
        Sign Up
      </button>
      <button
        @click="signUpWithGoogle"
        class="w-2/6 rounded-lg bg-black p-3 text-lg tracking-wide transition-all hover:text-primary active:tracking-widest max-sm:w-full"
      >
        Sign Up With Google
      </button>
    </div>
    <p v-if="errorMessage" class="text-center text-red-500">
      {{ errorMessage }}
    </p>
  </main>
</template>

<script setup>
import signInWithGoogle from "../utils/account/googleSignIn";
import signInWithEmail from "../utils/account/emailSignIn";
import setupUserDb from "../utils/account/setupUserDb";
import { useRouter } from "vue-router";
import { ref } from "vue";

const email = ref("");
const password = ref("");
const errorMessage = ref("");
const passwordConfirm = ref("");

const router = useRouter();

const updateErrorMessage = (error) => {
  errorMessage.value = error;
  setTimeout(() => {
    errorMessage.value = "";
  }, 3000);
};

const signUpWithGoogle = async () => {
  const user = await signInWithGoogle();
  if (user) {
    await setupUserDb(user);
    router.push("/diaries");
  }
};

const signUpWithEmail = async () => {
  if (
    email.value === "" ||
    password.value === "" ||
    passwordConfirm.value === ""
  ) {
    updateErrorMessage("Please fill in all fields!");
    return;
  }

  const emailRegex = /\S+@\S+\.\S+/;
  if (!emailRegex.test(email.value)) {
    updateErrorMessage("Please enter a valid email!");
    return;
  }

  if (password.value !== passwordConfirm.value) {
    updateErrorMessage("Passwords do not match!");
    return;
  }

  const result = await signInWithEmail(email.value, password.value);
  if (result[0] === "success") {
    await setupUserDb(result[1]);
    router.push("/diaries");
  } else {
    updateErrorMessage(result[1]);
  }
};
</script>
