// src/components/Checkbox.vue
<template>
  <label
    class="container relative flex cursor-pointer select-none items-center gap-2"
  >
    <input
      type="checkbox"
      class="hidden"
      :checked="internalChecked"
      @change="updateChecked"
    />
    <div
      :class="[
        'custom-checkbox h-6 w-6 rounded bg-light-background transition-all hover:bg-dark-text',
        internalChecked ? 'bg-primary hover:bg-primary hover:opacity-50' : '',
      ]"
    ></div>
    <span class="label text-xl">{{ label }}</span>
  </label>
</template>

<script setup>
import { ref, defineProps, defineEmits } from "vue";

const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
  label: {
    type: String,
    default: "",
  },
});

const emits = defineEmits(["update:modelValue"]);

const internalChecked = ref(props.modelValue);

const updateChecked = () => {
  internalChecked.value = !internalChecked.value;
  emits("update:modelValue", internalChecked.value);
};
</script>

// components/general/checkbox.tsx
import { useState } from "react";

type Props = {
  label: string;
  checked: boolean;
  updateChecked: (checked: boolean) => void;
};

export default function Checkbox({ label, checked, updateChecked }: Props) {
  const [isChecked, setIsChecked] = useState(checked);

  return (
    <label className="container relative flex cursor-pointer select-none items-center gap-2">
      <input
        type="checkbox"
        className="hidden"
        checked={isChecked}
        onChange={() => {
          setIsChecked(!isChecked);
          updateChecked(!isChecked);
        }}
      />
      <div
        className={`custom-checkbox h-6 w-6 rounded bg-light-background transition-all hover:bg-dark-text 
            ${isChecked ? "bg-primary hover:bg-primary hover:opacity-50" : ""}`}
      ></div>
      <span className="label text-xl">{label}</span>
    </label>
  );
}
